version: '3'
services:
  gallery:
    build: gallery/.
    container_name: "gallery"
    ports:
      - "3005:3005"
    depends_on:
      - mongoseed
  mongodb:
    image: mongo:4.4
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
#    volumes:
#      - mongodb:/data/db
    ports:
      - 27017:27017
    command: mongod
  mongoseed:
    container_name: "mongoseed"
    build: ./mongo-seed
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
      - CLIENT_ID=${CLIENT_ID:-photoprint}
      - CLIENT_SECRET=${CLIENT_SECRET:-secret}
    depends_on:
      - mongodb
  photoprint:
    build: photoprint/.
    container_name: "photoprint"
    environment:
      - CLIENT_ID=${CLIENT_ID:-photoprint}
      - CLIENT_SECRET=${CLIENT_SECRET:-secret}
      - SESSION_SECRET=${SESSION_SECRET:-changethistoconfigfile}
    ports:
      - "3000:3000"
    depends_on:
      - gallery
  attacker:
    build: attacker/.
    container_name: "attacker"
    environment:
      - CLIENT_ID=${CLIENT_ID:-photoprint}
      - CLIENT_SECRET=${CLIENT_SECRET:-secret}
      - SESSION_SECRET=${SESSION_SECRET:-changethistoconfigfile}
    ports:
      - "1337:1337"
    depends_on:
      - gallery
      - photoprint
  selenium:
    image: selenium/standalone-firefox-debug:latest
    ports:
      - "4444:4444"
      - "5900:5900"
#volumes:
#  mongodb: 